### ISSUE TITLE
Gas sensor quirk

### ISSUE THREAD

**Issue by wdoekes** [wdoekes/pe32proxsenspy_pub#2]
Log: 

<details>
<pre>
(see separate log)
</pre>
</details>

[separate-log.txt](https://github.com/wdoekes/pe32proxsenspy_pub/files/13739596/separate-log.txt)

Images:

![image](https://github.com/wdoekes/pe32proxsenspy_pub/assets/1225014/39b3c7c3-58bf-454d-8695-b1a7587744b1)

Earlier use is fine:

![image](https://github.com/wdoekes/pe32proxsenspy_pub/assets/1225014/3fb9c477-b136-454d-a812-712e9bab2341)

<details>
<pre>
19:00:57.097358 sent no_pulse, next=1703095317.0958269
19:01:15.343031 recalibrated: 16316->16317 18561->18560 (18184)
19:01:57.105232 sent no_pulse, next=1703095377.1038651
19:02:36.442261 recalibrated: 16317->16318 18560->18559 (18191)
19:02:57.130278 sent no_pulse, next=1703095437.1286638
19:03:57.131807 sent no_pulse, next=1703095497.1300197
19:03:57.544112 recalibrated: 16318->16319 18559->18558 (18227)
19:04:57.144054 sent no_pulse, next=1703095557.1420708
19:04:57.148863 Published: device_id=*** g_absolute_l=-1 g_relative_l=30690 g_flow_mlps=0 dbg_uptime=1379438224 dbg_version=pe32proxsenspy_pub-FIXME
19:05:18.643733 recalibrated: 16319->16320 18558->18557 (18224)
19:05:57.156838 sent no_pulse, next=1703095617.155501
19:06:39.748273 recalibrated: 16320->16321 18557->18556 (18227)
19:06:57.183349 sent no_pulse, next=1703095677.1819532
19:07:57.282720 sent no_pulse, next=1703095737.2808332
19:08:00.831585 recalibrated: 16321->16322 18556->18555 (18187)
19:08:57.286783 sent no_pulse, next=1703095797.2853298
19:09:21.922557 recalibrated: 16322->16323 18555->18554 (18222)
19:09:57.312482 sent no_pulse, next=1703095857.3109932
19:09:57.317145 Published: device_id=*** g_absolute_l=-1 g_relative_l=30690 g_flow_mlps=0 dbg_uptime=1379738393 dbg_version=pe32proxsenspy_pub-FIXME
19:10:43.020492 recalibrated: 16323->16324 18554->18553 (18247)
19:10:57.413774 sent no_pulse, next=1703095917.4113386
19:11:57.425958 sent no_pulse, next=1703095977.4245644
19:12:04.119200 recalibrated: 16324->16325 18553->18552 (18249)
19:12:57.433378 sent no_pulse, next=1703096037.4315767
19:13:25.210846 recalibrated: 16325->16326 18552->18551 (18229)
19:13:57.452858 sent no_pulse, next=1703096097.4504256
19:14:46.307213 recalibrated: 16326->16327 18551->18550 (18224)
19:14:57.455495 sent no_pulse, next=1703096157.4540749
19:14:57.460221 Published: device_id=*** g_absolute_l=-1 g_relative_l=30690 g_flow_mlps=0 dbg_uptime=1380038536 dbg_version=pe32proxsenspy_pub-FIXME
19:15:57.475899 sent no_pulse, next=1703096217.474525
19:16:07.410033 recalibrated: 16327->16328 18550->18549 (18223)
19:16:57.491300 sent no_pulse, next=1703096277.488953
19:17:28.512663 recalibrated: 16328->16329 18549->18548 (18224)
19:17:57.503666 sent no_pulse, next=1703096337.5023232
19:18:49.633772 recalibrated: 16329->16330 18548->18547 (18220)
19:18:57.538497 sent no_pulse, next=1703096397.5371573
19:19:57.639439 sent no_pulse, next=1703096457.6375718
19:19:57.643706 Published: device_id=*** g_absolute_l=-1 g_relative_l=30690 g_flow_mlps=0 dbg_uptime=1380338719 dbg_version=pe32proxsenspy_pub-FIXME
19:20:10.716319 recalibrated: 16330->16331 18547->18546 (18225)
19:20:57.649142 sent no_pulse, next=1703096517.647804
19:21:31.812277 recalibrated: 16331->16332 18546->18545 (18215)
19:21:57.659987 sent no_pulse, next=1703096577.6586287
19:22:52.890836 recalibrated: 16332->16333 18545->18544 (18222)
19:22:57.760141 sent no_pulse, next=1703096637.7583616
19:23:57.793760 sent no_pulse, next=1703096697.7923794
19:24:14.015946 recalibrated: 16333->16334 18544->18543 (18221)
19:24:57.815569 sent no_pulse, next=1703096757.8130326
19:24:57.820255 Published: device_id=*** g_absolute_l=-1 g_relative_l=30690 g_flow_mlps=0 dbg_uptime=1380638895 dbg_version=pe32proxsenspy_pub-FIXME
19:25:35.117529 recalibrated: 16334->16335 18543->18542 (18247)
19:25:57.829587 sent no_pulse, next=1703096817.8272283
19:26:42.826871 got (low) pulse 16942 [16335..18542] 0 (mL/s) now=1703096802.826106 next=1703134353.4824572 td=3129.22136259079
19:26:42.831772 Published: device_id=*** g_absolute_l=-1 g_relative_l=30700 g_flow_mlps=0 dbg_uptime=1380743907 dbg_version=pe32proxsenspy_pub-FIXME
19:26:56.218477 recalibrated: 16335->16336 18542->18541 (16402)
19:27:33.525918 got (high) pulse 17836 [16336..18541]
19:27:41.738955 got (low) pulse 17052 [16336..18541] 134 (mL/s) now=1703096861.738215 next=1703096960.2984614 td=8.213353872299194
19:27:41.744324 Published: device_id=*** g_absolute_l=-1 g_relative_l=30710 g_flow_mlps=134 dbg_uptime=1380802819 dbg_version=pe32proxsenspy_pub-FIXME
19:28:17.323917 recalibrated: 16336->16323 18541->18540 (16446)
19:29:20.380997 sent no_pulse, next=1703097020.379602
19:29:20.385808 Published: device_id=*** g_absolute_l=-1 g_relative_l=30710 g_flow_mlps=0 dbg_uptime=1380901461 dbg_version=pe32proxsenspy_pub-FIXME
19:29:38.422724 recalibrated: 16323->16324 18540->18539 (16446)
19:30:20.397216 sent no_pulse, next=1703097080.3957498
19:30:59.526161 recalibrated: 16324->16325 18539->18538 (16445)
19:31:20.416700 sent no_pulse, next=1703097140.415295
19:32:20.438672 sent no_pulse, next=1703097200.437325
19:32:20.643314 recalibrated: 16325->16326 18538->18537 (16441)
19:33:20.461396 sent no_pulse, next=1703097260.4600346
19:33:41.752939 recalibrated: 16326->16327 18537->18536 (16469)
19:34:20.561512 sent no_pulse, next=1703097320.5600758
19:34:20.570028 Published: device_id=*** g_absolute_l=-1 g_relative_l=30710 g_flow_mlps=0 dbg_uptime=1381201646 dbg_version=pe32proxsenspy_pub-FIXME
19:35:02.833352 recalibrated: 16327->16328 18536->18535 (16333)
19:35:20.575365 sent no_pulse, next=1703097380.5739884
19:36:20.582699 sent no_pulse, next=1703097440.581156
19:36:23.928484 recalibrated: 16328->16329 18535->18534 (16447)
19:37:20.588809 sent no_pulse, next=1703097500.5874274
19:37:45.010315 recalibrated: 16329->16330 18534->18533 (16439)
19:38:20.680874 sent no_pulse, next=1703097560.679524
19:39:06.101567 recalibrated: 16330->16331 18533->18532 (16445)
19:39:20.694685 sent no_pulse, next=1703097620.6932836
19:39:20.699363 Published: device_id=*** g_absolute_l=-1 g_relative_l=30710 g_flow_mlps=0 dbg_uptime=1381501775 dbg_version=pe32proxsenspy_pub-FIXME
19:40:05.794729 got (high) pulse 17883 [16331..18532]
19:40:07.417433 got (low) pulse 16815 [16331..18532] 678 (mL/s) now=1703097607.4166093 next=1703097626.8865943 td=1.6224987506866455
19:40:07.422370 Published: device_id=*** g_absolute_l=-1 g_relative_l=30720 g_flow_mlps=678 dbg_uptime=1381548498 dbg_version=pe32proxsenspy_pub-FIXME
19:40:17.554418 got (high) pulse 18109 [16331..18532]
19:40:18.873241 got (low) pulse 16950 [16331..18532] 834 (mL/s) now=1703097618.8724933 next=1703097634.6968112 td=1.3186931610107422
19:40:18.878142 Published: device_id=*** g_absolute_l=-1 g_relative_l=30730 g_flow_mlps=834 dbg_uptime=1381559953 dbg_version=pe32proxsenspy_pub-FIXME
19:40:27.182581 recalibrated: 16331->16332 18532->18531 (16465)
19:40:29.007704 got (high) pulse 17826 [16332..18531]
19:40:30.224130 got (low) pulse 16869 [16332..18531] 904 (mL/s) now=1703097630.2233887 next=1703097644.8191032 td=1.2163095474243164
19:40:30.229044 Published: device_id=*** g_absolute_l=-1 g_relative_l=30740 g_flow_mlps=904 dbg_uptime=1381571304 dbg_version=pe32proxsenspy_pub-FIXME
19:40:40.562617 got (high) pulse 18096 [16332..18531]
19:40:41.680641 got (low) pulse 17020 [16332..18531] 984 (mL/s) now=1703097641.6798844 next=1703097655.0954556 td=1.117964267730713
19:40:41.685652 Published: device_id=*** g_absolute_l=-1 g_relative_l=30750 g_flow_mlps=984 dbg_uptime=1381582761 dbg_version=pe32proxsenspy_pub-FIXME
19:40:51.921122 got (high) pulse 17817 [16332..18531]
19:40:53.238298 got (low) pulse 16914 [16332..18531] 835 (mL/s) now=1703097653.2375433 next=1703097669.0420516 td=1.317042350769043
19:40:53.243237 Published: device_id=*** g_absolute_l=-1 g_relative_l=30760 g_flow_mlps=835 dbg_uptime=1381594319 dbg_version=pe32proxsenspy_pub-FIXME
19:41:03.380759 got (high) pulse 17815 [16332..18531]
19:41:04.901208 got (low) pulse 16782 [16332..18531] 724 (mL/s) now=1703097664.9004564 next=1703097683.1449966 td=1.5203783512115479
19:41:04.906017 Published: device_id=*** g_absolute_l=-1 g_relative_l=30770 g_flow_mlps=724 dbg_uptime=1381605981 dbg_version=pe32proxsenspy_pub-FIXME
19:41:14.938093 got (high) pulse 17979 [16332..18531]
19:41:16.459389 got (low) pulse 16880 [16332..18531] 723 (mL/s) now=1703097676.4586337 next=1703097694.7127154 td=1.5211734771728516
19:41:16.464317 Published: device_id=*** g_absolute_l=-1 g_relative_l=30780 g_flow_mlps=723 dbg_uptime=1381617540 dbg_version=pe32proxsenspy_pub-FIXME
19:41:26.493634 got (high) pulse 17995 [16332..18531]
19:41:27.912054 got (low) pulse 16962 [16332..18531] 776 (mL/s) now=1703097687.9113002 next=1703097704.9308763 td=1.4182980060577393
19:41:27.916940 Published: device_id=*** g_absolute_l=-1 g_relative_l=30790 g_flow_mlps=776 dbg_uptime=1381628992 dbg_version=pe32proxsenspy_pub-FIXME
19:41:38.045268 got (high) pulse 17979 [16332..18531]
19:41:39.363476 got (low) pulse 16991 [16332..18531] 834 (mL/s) now=1703097699.3627298 next=1703097715.1840637 td=1.3184444904327393
19:41:39.371793 Published: device_id=*** g_absolute_l=-1 g_relative_l=30800 g_flow_mlps=834 dbg_uptime=1381640448 dbg_version=pe32proxsenspy_pub-FIXME
19:41:48.288181 recalibrated: 16332->16325 18531->18530 (16562)
19:41:49.610329 got (high) pulse 17955 [16325..18530]
19:41:50.727506 got (low) pulse 17055 [16325..18530] 985 (mL/s) now=1703097710.7266665 next=1703097724.1302385 td=1.116964340209961
19:41:50.732319 Published: device_id=*** g_absolute_l=-1 g_relative_l=30810 g_flow_mlps=985 dbg_uptime=1381651808 dbg_version=pe32proxsenspy_pub-FIXME
19:42:01.070490 got (high) pulse 17927 [16325..18530]
19:42:02.391293 got (low) pulse 16731 [16325..18530] 833 (mL/s) now=1703097722.390528 next=1703097738.2384808 td=1.3206627368927002
19:42:02.396134 Published: device_id=*** g_absolute_l=-1 g_relative_l=30820 g_flow_mlps=833 dbg_uptime=1381663472 dbg_version=pe32proxsenspy_pub-FIXME
19:42:12.530336 got (high) pulse 17891 [16325..18530]
19:42:13.851717 got (low) pulse 16901 [16325..18530] 833 (mL/s) now=1703097733.8509476 next=1703097749.705804 td=1.3212380409240723
19:42:13.856537 Published: device_id=*** g_absolute_l=-1 g_relative_l=30830 g_flow_mlps=833 dbg_uptime=1381674932 dbg_version=pe32proxsenspy_pub-FIXME
19:42:23.992158 got (high) pulse 17983 [16325..18530]
19:42:25.416555 got (low) pulse 16946 [16325..18530] 772 (mL/s) now=1703097745.4158084 next=1703097762.5080345 td=1.4243521690368652
19:42:25.425137 Published: device_id=*** g_absolute_l=-1 g_relative_l=30840 g_flow_mlps=772 dbg_uptime=1381686501 dbg_version=pe32proxsenspy_pub-FIXME
19:42:35.666617 got (high) pulse 18060 [16325..18530]
19:42:37.091235 got (low) pulse 16975 [16325..18530] 772 (mL/s) now=1703097757.0904934 next=1703097774.184336 td=1.4244868755340576
19:42:37.099932 Published: device_id=*** g_absolute_l=-1 g_relative_l=30850 g_flow_mlps=772 dbg_uptime=1381698176 dbg_version=pe32proxsenspy_pub-FIXME
19:42:47.128815 got (high) pulse 17814 [16325..18530]
19:42:48.552884 got (low) pulse 17049 [16325..18530] 773 (mL/s) now=1703097768.5521111 next=1703097785.6390414 td=1.4239108562469482
19:42:48.557717 Published: device_id=*** g_absolute_l=-1 g_relative_l=30860 g_flow_mlps=773 dbg_uptime=1381709633 dbg_version=pe32proxsenspy_pub-FIXME
19:42:58.689941 got (high) pulse 17881 [16325..18530]
19:43:00.012537 got (low) pulse 17031 [16325..18530] 832 (mL/s) now=1703097780.0117278 next=1703097795.8805718 td=1.3224036693572998
19:43:00.021445 Published: device_id=*** g_absolute_l=-1 g_relative_l=30870 g_flow_mlps=832 dbg_uptime=1381721097 dbg_version=pe32proxsenspy_pub-FIXME
19:43:09.445215 recalibrated: 16325->16324 18530->18529 (16559)
19:43:10.767715 got (high) pulse 17875 [16324..18529]
19:43:11.989356 got (low) pulse 16973 [16324..18529] 900 (mL/s) now=1703097791.9886093 next=1703097806.6484537 td=1.221653699874878
19:43:11.998004 Published: device_id=*** g_absolute_l=-1 g_relative_l=30880 g_flow_mlps=900 dbg_uptime=1381733074 dbg_version=pe32proxsenspy_pub-FIXME
19:43:22.434624 got (high) pulse 17959 [16324..18529]
19:43:23.758296 got (low) pulse 16669 [16324..18529] 832 (mL/s) now=1703097803.7564416 next=1703097819.6257463 td=1.3224420547485352
19:43:23.766746 Published: device_id=*** g_absolute_l=-1 g_relative_l=30890 g_flow_mlps=832 dbg_uptime=1381744843 dbg_version=pe32proxsenspy_pub-FIXME
19:43:33.905345 got (high) pulse 17963 [16324..18529]
19:43:35.124438 got (low) pulse 16963 [16324..18529] 902 (mL/s) now=1703097815.1236846 next=1703097829.7513254 td=1.2189700603485107
19:43:35.129255 Published: device_id=*** g_absolute_l=-1 g_relative_l=30900 g_flow_mlps=902 dbg_uptime=1381756205 dbg_version=pe32proxsenspy_pub-FIXME
19:43:45.359387 got (high) pulse 17980 [16324..18529]
19:43:46.780105 got (low) pulse 16957 [16324..18529] 774 (mL/s) now=1703097826.7793489 next=1703097843.8264794 td=1.4205942153930664
19:43:46.784799 Published: device_id=*** g_absolute_l=-1 g_relative_l=30910 g_flow_mlps=774 dbg_uptime=1381767860 dbg_version=pe32proxsenspy_pub-FIXME
19:43:57.125257 got (high) pulse 17855 [16324..18529]
19:43:58.651426 got (low) pulse 17020 [16324..18529] 721 (mL/s) now=1703097838.650628 next=1703097856.962614 td=1.525998830795288
19:43:58.660158 Published: device_id=*** g_absolute_l=-1 g_relative_l=30920 g_flow_mlps=721 dbg_uptime=1381779736 dbg_version=pe32proxsenspy_pub-FIXME
19:44:09.104037 got (high) pulse 17799 [16324..18529]
19:44:17.016935 sent no_pulse, next=1703097917.0154874
19:44:17.025452 Published: device_id=*** g_absolute_l=-1 g_relative_l=30920 g_flow_mlps=0 dbg_uptime=1381798101 dbg_version=pe32proxsenspy_pub-FIXME
19:44:30.606829 recalibrated: 16324->16323 18529->18581 (18595)
19:45:17.045724 sent no_pulse, next=1703097977.0443478
19:45:51.731358 recalibrated: 16323->16324 18581->18601 (18600)
19:46:17.074639 sent no_pulse, next=1703098037.0732496
19:47:12.847736 recalibrated: 16324->16325 18601->18602 (18570)
19:47:17.113589 sent no_pulse, next=1703098097.1121974
19:48:17.135067 sent no_pulse, next=1703098157.1336944
19:48:33.974723 recalibrated: 16325->16326 18602->18602 (18578)
19:49:17.163678 sent no_pulse, next=1703098217.16228
19:49:17.171617 Published: device_id=*** g_absolute_l=-1 g_relative_l=30920 g_flow_mlps=0 dbg_uptime=1382098248 dbg_version=pe32proxsenspy_pub-FIXME
19:49:55.071658 recalibrated: 16326->16327 18602->18604 (18458)
19:50:17.264430 sent no_pulse, next=1703098277.263082
19:51:16.158873 recalibrated: 16327->16328 18604->18603 (18529)
19:51:17.277777 sent no_pulse, next=1703098337.276317
19:52:17.376073 sent no_pulse, next=1703098397.3747013
19:52:37.239947 recalibrated: 16328->16329 18603->18602 (18554)
19:53:17.471438 sent no_pulse, next=1703098457.46966
19:53:58.325026 recalibrated: 16329->16330 18602->18602 (18581)
19:54:17.488659 sent no_pulse, next=1703098517.4872057
19:54:17.496555 Published: device_id=*** g_absolute_l=-1 g_relative_l=30920 g_flow_mlps=0 dbg_uptime=1382398573 dbg_version=pe32proxsenspy_pub-FIXME
19:54:20.939136 Analog readings: 18576 18604 18580 18579 18603 18571 18574 18604 18574 18602 18573 18597 18577 18605 18575 18552 18577 18599 18578 18601
19:54:22.967282 Analog readings: 18581 18583 18580 18564 18577 18572 18574 18582 18601 18579 18584 18577 18584 18578 18590 18579 18580 18603 18600 18538
19:54:24.994233 Analog readings: 18563 18553 18556 18537 18547 18548 18550 18551 18574 18533 18568 18543 18552 18559 18563 18606 18579 18580 18607 18580
19:54:27.026822 Analog readings: 18605 18583 18608 18559 18578 18583 18578 18583 18565 18577 18603 18574 18578 18579 18575 18580 18581 18579 18541 18574
19:54:29.057761 Analog readings: 18606 18579 18579 18558 18556 18579 18578 18580 18527 18578 18578 18607 18581 18603 18573 18579 18548 18607 18578 18594
19:54:31.089463 Analog readings: 18578 18602 18577 18604 18579 18582 18576 18572 18596 18578 18605 18577 18531 18572 18603 18574 18575 18581 18582 18606
19:54:33.121420 Analog readings: 18578 18574 18579 18578 18603 18575 18577 18579 18604 18578 18575 18581 18535 18602 18567 18579 18578 18136 18347 18575
19:54:35.148499 Analog readings: 18579 18578 18578 18576 18580 18579 18580 18575 18573 18597 18572 18598 18572 18595 18571 18573 18570 18522 18571 18589
19:54:37.179416 Analog readings: 18539 18547 18554 18574 18546 18551 18551 18570 18532 18547 18560 18553 18578 18606 18582 18581 18580 18604 18576 18577
19:54:39.211375 Analog readings: 18579 18577 18572 18558 18578 18578 18580 18606 18582 18580 18580 18535 18579 18604 18578 18577 18565 18603 18580 18577
19:54:41.243161 Analog readings: 18577 18535 18577 18586 18573 18543 18538 18577 18604 18579 18579 18575 18575 18583 18574 18605 18454 18602 18577 18577
19:54:43.277299 Analog readings: 18600 18591 18571 18534 18579 18453 18506 18580 18572 18577 18569 18572 18598 18567 18558 18580 18572 18593 18573 18574
19:54:45.304518 Analog readings: 18577 18579 18605 18580 18604 18575 18600 18578 18579 18578 18578 18553 18577 18581 18591 18579 18580 18603 18575 18602
19:54:47.336661 Analog readings: 18524 18578 18580 18575 18593 18580 18579 18604 18577 18510 18530 18578 18587 18574 18581 18579 18568 18575 18579 18579
19:54:49.364541 Analog readings: 18577 18582 18541 18581 18556 18523 18564 18588 18562 18557 18577 18566 18528 18549 18552 18558 18541 18573 18555 18584
19:54:51.393351 Analog readings: 18540 18510 18551 18561 18567 18515 18588 18581 18580 18571 18601 18555 18575 18578 18577 18571 18605 18574 18580 18545
19:54:53.427127 Analog readings: 18579 18597 18581 18576 18577 18574 18598 18570 18573 18595 18574 18579 18602 18581 18604 18575 18604 18581 18577 18552
19:54:55.459034 Analog readings: 18577 18579 18577 18602 18578 18601 18581 18605 18575 18608 18571 18581 18578 18604 18504 18577 18580 18578 18570 18603
19:54:57.491248 Analog readings: 18580 18578 18599 18565 18596 18577 18581 18576 18600 18578 18555 18568 18603 18602 18512 18590 18579 18580 18513 18576
19:54:59.520716 Analog readings: 18605 18579 18519 18577 18601 18579 18581 18581 18577 18579 18598 18580 18578 18577 18578 18603 18581 18568 18576 18577
19:55:01.549780 Analog readings: 18607 18578 18577 18580 18579 18605 18577 18580 18537 18545 18542 18544 18546 18550 18544 18541 18562 18536 18577 18538
19:55:03.584111 Analog readings: 18576 18580 18577 18583 18473 18335 18602 18582 18598 18606 18580 18599 18578 18537 18593 18579 18572 18578 18581 18555
19:55:05.614050 Analog readings: 18576 18579 18471 18599 18581 18580 18579 18576 18578 18605 18580 18577 18576 18545 18566 18581 18579 18580 18603 18577
19:55:07.644197 Analog readings: 18579 18581 18580 18602 18567 18578 18581 18579 18492 18602 18578 18580 18579 18603 18581 18579 18581 18579 18580 18589
19:55:09.676572 Analog readings: 18579 18581 18580 18604 18581 18580 18578 18582 18575 18581 18571 18568 18576 18567 18565 18568 18572 18573 18596 18575
19:55:11.709418 Analog readings: 18603 18580 18309 18480 18579 18580 18580 18580 18556 18577 18579 18580 18581 18605 18578 18580 18579 18581 18605 18578
19:55:13.740322 Analog readings: 18428 18544 18485 18571 18541 18549 18555 18554 18574 18553 18575 18553 18572 18545 18576 18604 18583 18606 18578 18577
19:55:15.769992 Analog readings: 18573 18575 18603 18571 18576 18578 18396 18602 18581 18574 18579 18580 18605 18580 18577 18580 18571 18587 18579 18604
19:55:17.495946 sent no_pulse, next=1703098577.4941201
19:55:17.801011 Analog readings: 18562 18605 18576 18590 18582 18578 18580 18601 18579 18578 18576 18600 18575 18563 18579 18579 18581 18546 18580 18581
19:55:19.018502 Analog readings: 18580 18534 18592 18577 18578 18580 18548 18596 18575 18493 18577
19:55:19.526959 recalibrated: 16330->16331 18602->18604 (18576)
19:56:17.593769 sent no_pulse, next=1703098637.592376
19:56:40.598640 recalibrated: 16331->16332 18604->18604 (18602)
19:57:17.683725 sent no_pulse, next=1703098697.6823413
19:58:01.676095 recalibrated: 16332->16333 18604->18603 (18564)
19:58:17.687999 sent no_pulse, next=1703098757.686617
19:59:17.702749 sent no_pulse, next=1703098817.701208
19:59:17.707585 Published: device_id=*** g_absolute_l=-1 g_relative_l=30920 g_flow_mlps=0 dbg_uptime=1382698783 dbg_version=pe32proxsenspy_pub-FIXME
19:59:22.771800 recalibrated: 16333->16334 18603->18605 (18522)
</pre>
</details>

The 40L value is likely average, and should not be in the graph. The question remains:
- why was there no push between 23:00 and 07:00.
- is the spike high? or just fine, but looks off because we had no 0-mpls pushes in between?

![image](https://github.com/wdoekes/pe32proxsenspy_pub/assets/1225014/80eec1b6-ca66-447b-91f3-6d75a3e1eaa2)

```
23:24:23.511674 Published: device_id=*** g_absolute_l=-1 g_relative_l=30920 g_flow_mlps=0 dbg_uptime=1395004587 dbg_version=pe32proxsenspy_pub-FIXME
23:29:23.649873 Published: device_id=*** g_absolute_l=-1 g_relative_l=30920 g_flow_mlps=0 dbg_uptime=1395304725 dbg_version=pe32proxsenspy_pub-FIXME
23:32:52.900797 Published: device_id=*** g_absolute_l=-1 g_relative_l=30930 g_flow_mlps=0 dbg_uptime=1395513976 dbg_version=pe32proxsenspy_pub-FIXME
07:23:41.013988 Published: device_id=*** g_absolute_l=-1 g_relative_l=30940 g_flow_mlps=832 dbg_uptime=1423762090 dbg_version=pe32proxsenspy_pub-FIXME
07:23:52.170057 Published: device_id=*** g_absolute_l=-1 g_relative_l=30950 g_flow_mlps=832 dbg_uptime=1423773246 dbg_version=pe32proxsenspy_pub-FIXME
07:24:03.426986 Published: device_id=*** g_absolute_l=-1 g_relative_l=30960 g_flow_mlps=832 dbg_uptime=1423784503 dbg_version=pe32proxsenspy_pub-FIXME
07:24:15.495085 Published: device_id=*** g_absolute_l=-1 g_relative_l=30970 g_flow_mlps=677 dbg_uptime=1423796571 dbg_version=pe32proxsenspy_pub-FIXME
07:24:35.070494 Published: device_id=*** g_absolute_l=-1 g_relative_l=30970 g_flow_mlps=0 dbg_uptime=1423816146 dbg_version=pe32proxsenspy_pub-FIXME
07:29:35.293549 Published: device_id=*** g_absolute_l=-1 g_relative_l=30970 g_flow_mlps=0 dbg_uptime=1424116369 dbg_version=pe32proxsenspy_pub-FIXME
07:34:35.512769 Published: device_id=*** g_absolute_l=-1 g_relative_l=30970 g_flow_mlps=0 dbg_uptime=1424416588 dbg_version=pe32proxsenspy_pub-FIXME
```

**Comment by wdoekes** [comment]
Also, it stops publishing periodic updates when there is no gas usage:
```
Dec 24 13:37:28 framboos.kiwi pe32proxsenspy2_pub[28003]: sent no_pulse, next=1703421508.8404968
Dec 24 13:38:28 framboos.kiwi pe32proxsenspy2_pub[28003]: sent no_pulse, next=1703421568.856849
Dec 24 13:39:28 framboos.kiwi pe32proxsenspy2_pub[28003]: sent no_pulse, next=1703421628.8760037
```
```
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]: - task <Task finished name='dead_mans_switch' coro=<dead_mans_switch() done, defined at /srv/pe32proxsenspy_pub/pe32proxsenspy_pub.py:33> exception=DeadMansSwitchTripped('more than 86400573 ms have passed without changes')> was already done
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]: Traceback (most recent call last):
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]:   File "/srv/pe32proxsenspy_pub/pe32proxsenspy_pub.py", line 361, in <module>
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]:     loop.run_until_complete(main_coro)
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]:     return future.result()
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]:   File "/srv/pe32proxsenspy_pub/pe32proxsenspy_pub.py", line 333, in main
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]:     task.result()  # raises exceptions if any
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]:   File "/srv/pe32proxsenspy_pub/pe32proxsenspy_pub.py", line 38, in dead_mans_switch
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]:     raise DeadMansSwitchTripped(
Dec 24 13:39:59 framboos.kiwi pe32proxsenspy2_pub[28003]: __main__.DeadMansSwitchTripped: more than 86400573 ms have passed without changes
Dec 24 13:39:59 framboos.kiwi systemd[1]: pe32proxsenspy2_pub.service: Main process exited, code=exited, status=1/FAILURE
Dec 24 13:39:59 framboos.kiwi systemd[1]: pe32proxsenspy2_pub.service: Failed with result 'exit-code'.
Dec 24 13:40:14 framboos.kiwi systemd[1]: pe32proxsenspy2_pub.service: Scheduled restart job, restart counter is at 1.
Dec 24 13:40:14 framboos.kiwi systemd[1]: Stopped PE32 proximity sensor exporter.
```
```
Dec 24 13:40:14 framboos.kiwi systemd[1]: Started PE32 proximity sensor exporter.
Dec 24 13:40:15 framboos.kiwi pe32proxsenspy2_pub[23316]: pid 23316: send SIGINT or SIGTERM to exit.
Dec 24 13:40:15 framboos.kiwi pe32proxsenspy2_pub[23316]: Using selector: EpollSelector
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]: - task <Task finished name='dead_mans_switch' coro=<dead_mans_switch() done, defined at /srv/pe32proxsenspy_pub/pe32proxsenspy_pub.py:33> exception=DeadMansSwitchTripped('more than 86400160 ms have passed without changes')> was already done
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]: Traceback (most recent call last):
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]:   File "/srv/pe32proxsenspy_pub/pe32proxsenspy_pub.py", line 361, in <module>
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]:     loop.run_until_complete(main_coro)
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]:     return future.result()
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]:   File "/srv/pe32proxsenspy_pub/pe32proxsenspy_pub.py", line 333, in main
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]:     task.result()  # raises exceptions if any
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]:   File "/srv/pe32proxsenspy_pub/pe32proxsenspy_pub.py", line 38, in dead_mans_switch
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]:     raise DeadMansSwitchTripped(
Dec 25 13:40:16 framboos.kiwi pe32proxsenspy2_pub[23316]: __main__.DeadMansSwitchTripped: more than 86400160 ms have passed without changes
Dec 25 13:40:16 framboos.kiwi systemd[1]: pe32proxsenspy2_pub.service: Main process exited, code=exited, status=1/FAILURE
Dec 25 13:40:16 framboos.kiwi systemd[1]: pe32proxsenspy2_pub.service: Failed with result 'exit-code'.
Dec 25 13:40:31 framboos.kiwi systemd[1]: pe32proxsenspy2_pub.service: Scheduled restart job, restart counter is at 2.
Dec 25 13:40:31 framboos.kiwi systemd[1]: Stopped PE32 proximity sensor exporter.
```
```
Dec 25 13:40:31 framboos.kiwi systemd[1]: Started PE32 proximity sensor exporter.
Dec 25 13:40:32 framboos.kiwi pe32proxsenspy2_pub[432]: pid 432: send SIGINT or SIGTERM to exit.
Dec 25 13:40:32 framboos.kiwi pe32proxsenspy2_pub[432]: Using selector: EpollSelector
```
